### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by zaharPonimash** [KvanTTT/MathExpressions.NET#11]
Здравствуйте!

Я прочитал Вашу статью на хабре(https://habr.com/ru/post/150043/), очень понравилась Ваша библиотека.
К сожалению, ее нельзя использовать т.к. в проекте нет файла лицензии. Не могли бы Вы ее лицензировать?

И спасибо за Ваш труд!

**Comment by KvanTTT** [comment]
Готово, добавил лицензию Apache-2.0

**Comment by zaharPonimash** [comment]
Спасибо!
